"""Added last name

Revision ID: 14e7e86bd23c
Revises: cc6a8244d27e
Create Date: 2025-10-09 21:59:36.612004

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "14e7e86bd23c"
down_revision: Union[str, Sequence[str], None] = "cc6a8244d27e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("player", sa.Column("last_name", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("player", "last_name")
    # ### end Alembic commands ###
