"""Removed last name

Revision ID: 8cb434f843c9
Revises: 14e7e86bd23c
Create Date: 2025-10-09 22:00:04.499271

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8cb434f843c9"
down_revision: Union[str, Sequence[str], None] = "14e7e86bd23c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("player", "last_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("player", sa.Column("last_name", sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
