"""Initial schema

Revision ID: cc6a8244d27e
Revises: 
Create Date: 2025-10-09 21:56:15.232144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from fussball.database.tables import GUID


# revision identifiers, used by Alembic.
revision: str = 'cc6a8244d27e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_id'), 'player', ['id'], unique=True)
    op.create_index(op.f('ix_player_name'), 'player', ['name'], unique=False)
    op.create_table('team',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('team_player_1_id', GUID(), nullable=False),
    sa.Column('team_player_2_id', GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_player_1_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['team_player_2_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_id'), 'team', ['id'], unique=True)
    op.create_table('match',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('winning_team_id', GUID(), nullable=False),
    sa.Column('losing_team_id', GUID(), nullable=False),
    sa.Column('winning_team_score', sa.Integer(), nullable=False),
    sa.Column('losing_team_score', sa.Integer(), nullable=False),
    sa.CheckConstraint('losing_team_score >= 0 AND losing_team_score != 10', name='losing_team_score_check'),
    sa.CheckConstraint('winning_team_score = 10', name='winning_team_score_check'),
    sa.ForeignKeyConstraint(['losing_team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['winning_team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_created_at'), 'match', ['created_at'], unique=False)
    op.create_index(op.f('ix_match_id'), 'match', ['id'], unique=True)
    op.create_index(op.f('ix_match_losing_team_id'), 'match', ['losing_team_id'], unique=False)
    op.create_index(op.f('ix_match_winning_team_id'), 'match', ['winning_team_id'], unique=False)
    op.create_table('player_rating',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('match_id', GUID(), nullable=False),
    sa.Column('player_id', GUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_rating_id'), 'player_rating', ['id'], unique=True)
    op.create_table('team_match',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('team_id', GUID(), nullable=False),
    sa.Column('match_id', GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_match_id'), 'team_match', ['id'], unique=True)
    op.create_table('team_rating',
    sa.Column('id', GUID(), nullable=False),
    sa.Column('team_match_id', GUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_match_id'], ['team_match.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_rating_id'), 'team_rating', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_rating_id'), table_name='team_rating')
    op.drop_table('team_rating')
    op.drop_index(op.f('ix_team_match_id'), table_name='team_match')
    op.drop_table('team_match')
    op.drop_index(op.f('ix_player_rating_id'), table_name='player_rating')
    op.drop_table('player_rating')
    op.drop_index(op.f('ix_match_winning_team_id'), table_name='match')
    op.drop_index(op.f('ix_match_losing_team_id'), table_name='match')
    op.drop_index(op.f('ix_match_id'), table_name='match')
    op.drop_index(op.f('ix_match_created_at'), table_name='match')
    op.drop_table('match')
    op.drop_index(op.f('ix_team_id'), table_name='team')
    op.drop_table('team')
    op.drop_index(op.f('ix_player_name'), table_name='player')
    op.drop_index(op.f('ix_player_id'), table_name='player')
    op.drop_table('player')
    # ### end Alembic commands ###
